apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: demo-application
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP