apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "mysql.secrets" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  db-password: ZGVtbw==