apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.pvc" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.storage }}
