apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - name: mysql
    port: {{ .Values.mysql.service.port }}
    targetPort: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}