apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "mychart.mysql.secrets" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    app: mysql
data:
  db-password: ZGVtbw==