apiVersion: v1
kind: Service
metadata:
  name: {{ template "wordpress.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
  - name: http
    port: {{ .Values.wordpress.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}