apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: demo-application
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql